Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-08, with the labels that each got.

#553 Update start script to wait for ipamd health check
  scripts/install-aws.sh
Labels: bug

#569 Hide health check output
  scripts/install-aws.sh
Labels: enhancement

#570 Support c5.12xlarge and c5.24xlarge
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#578 Remove unused env variable
  config/v1.5/aws-k8s-cni.yaml
Labels: tech debt

#580 Improve tests a bit
  .dockerignore
  Makefile
  main_test.go
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/networkutils/network.go
  pkg/networkutils/network_test.go
  testdata/executable
  testdata/regular-file.txt
Labels: testing

#554 Update Calico version to v3.8.1
  config/v1.5/calico.yaml
Labels: calico, enhancement

#572 update list of instances to be more metal \m/
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#577 Bump portmap version #499
  Makefile
Labels: enhancement

#597 Document AWS_VPC_K8S_CNI_VETHPREFIX #298
  README.md
  plugins/routed-eni/cni.go
  scripts/install-aws.sh
Labels: documentation
