Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-06, with the labels that each got.

#501 Add env var to override introspection bind address
  README.md
  ipamd/introspect.go
Labels: enhancement, feature request

#510 Support c5.12xlarge and c5.24xlarge
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#512 Fix introspection port in troubleshooting docs
  docs/troubleshooting.md
Labels: documentation

#513 Update kubeconfig lookup order for eksctl nodegroups
  scripts/aws-cni-support.sh
Labels: bug, enhancement
