Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-10, with the labels that each got.

#622 Add environment variable to configure MTU
  README.md
  pkg/networkutils/network.go
  pkg/networkutils/network_test.go
  plugins/routed-eni/driver/driver.go
Labels: enhancement, feature request

#645 Add shutdown listener
  ipamd/datastore/data_store.go
  ipamd/ipamd.go
  ipamd/ipamd_test.go
  ipamd/rpc_handler.go
  scripts/install-aws.sh
Labels: enhancement

#648 Add IPs to the first ENI on startup
  ipamd/ipamd.go
  ipamd/ipamd_test.go
Labels: enhancement

#646 Log security groups correctly
  pkg/awsutils/awsutils.go
Labels: tech debt

#667 Avoid trying tearing down NS
  pkg/k8sapi/discovery.go
  plugins/routed-eni/cni.go
  plugins/routed-eni/driver/driver.go
Labels: bug

#612 Introduce a minimum target for ENI IPs
  README.md
  ipamd/datastore/data_store.go
  ipamd/datastore/data_store_test.go
  ipamd/ipamd.go
Labels: enhancement
