Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-05, with the labels that each got.

#429 Modify max ENI check to allow for IP increase
  Gopkg.lock
  ipamd/ipamd.go
  pkg/awsutils/awsutils.go
Labels: bug

#428 bump aws/aws-sdk-go to v1.19.21
  go.mod
  go.sum
Labels: tech debt

#413 Update CNI metrics
  .gitignore
  Makefile
  cni-metrics-helper/cni-metrics-helper.go
  cni-metrics-helper/metrics/cni_metrics.go
  cni-metrics-helper/metrics/cni_test1.data
  cni-metrics-helper/metrics/metrics.go
  cni-metrics-helper/metrics/metrics_test.go
  config/v1.4/cni_metrics_helper.yaml
  pkg/ec2metadatawrapper/ec2metadatawrapper.go
  pkg/ec2metadatawrapper/ec2metadatawrapper_test.go
  pkg/ec2metadatawrapper/mocks/mock_ec2metadatawrapper.go
  pkg/ec2wrapper/ec2wrapper.go
  pkg/ec2wrapper/ec2wrapper_test.go
  pkg/k8sapi/discovery.go
  pkg/publisher/mock_publisher/mock_publisher.go
  pkg/publisher/publisher.go
  pkg/publisher/publisher_test.go
  scripts/dockerfiles/Dockerfile.metrics
Labels: enhancement, tech debt

#438 Update changelog
  CHANGELOG.md
Labels: documentation

#447 Update config and changelog
  CHANGELOG.md
  config/v1.4/aws-k8s-cni-1.10.yaml
  config/v1.4/aws-k8s-cni.yaml
  config/v1.4/cni-metrics-helper.yaml
Labels: documentation

#449 Exit early if we can't find current pods
  Gopkg.lock
  ipamd/ipamd.go
  pkg/k8sapi/discovery.go
Labels: bug

#451 Switch from skel.PluginMain to skel.PluginMainWithError, as the log h…
  plugins/routed-eni/cni.go
Labels: enhancement

#452 No pods is not an error
  ipamd/ipamd.go
Labels: bug

#453 No pods is not an error
  ipamd/ipamd.go
Labels: bug

#459 Update instance types
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#457 If GetAttachedENIs has problems, still exit the loop
  ipamd/ipamd.go
Labels: bug

#458 Avoid using force detach of ENIs
  pkg/awsutils/awsutils.go
Labels: bug

#467 Remove error message from Prometheus labels
  ipamd/ipamd.go
Labels: bug

#461 Improve WARM_IP_TARGET handling
  config/v1.3/aws-k8s-cni.yaml
  config/v1.4/calico.yaml
  config/v1.4/cni_metrics_helper.yaml
  ipamd/datastore/data_store.go
  ipamd/datastore/data_store_test.go
  ipamd/introspect.go
  ipamd/ipamd.go
  ipamd/metrics.go
  mocks/awsutils_mocks.go
  pkg/awsutils/awsutils.go
  pkg/k8sapi/discovery.go
  vendor/github.com/deckarep/golang-set/.gitignore
  vendor/github.com/deckarep/golang-set/.travis.yml
  vendor/github.com/deckarep/golang-set/LICENSE
  vendor/github.com/deckarep/golang-set/README.md
  vendor/github.com/deckarep/golang-set/bench_test.go
  vendor/github.com/deckarep/golang-set/iterator.go
  vendor/github.com/deckarep/golang-set/iterator_example_test.go
  vendor/github.com/deckarep/golang-set/set.go
  vendor/github.com/deckarep/golang-set/set_test.go
  vendor/github.com/deckarep/golang-set/threadsafe.go
  vendor/github.com/deckarep/golang-set/threadsafe_test.go
  vendor/github.com/deckarep/golang-set/threadunsafe.go
Labels: bug, enhancement, feature request, priority/P0

#473 Update logging format to align messages
  cni-metrics-helper/metrics/metrics.go
  ipamd/introspect.go
  ipamd/ipamd.go
  pkg/eniconfig/eniconfig.go
  pkg/k8sapi/discovery.go
  pkg/utils/logger/logger.go
Labels: enhancement

#478 Update metrics-helper link and readme
  Makefile
  README.md
  docs/troubleshooting.md
Labels: documentation

#481 Update documentation
  cni-metrics-helper/README.md
  cni-metrics-helper/cni-metrics-helper.go
  docs/cni-proposal.md
  docs/images/ipam.png
  docs/images/ping.png
  docs/images/ping2external.png
  docs/images/wire-network.png
  docs/troubleshooting.md
  ipamd/datastore/data_store_test.go
Labels: documentation

#485 Remove unused function
  ipamd/ipamd.go
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/mocks/awsutils_mocks.go
Labels: tech debt
