Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-11, with the labels that each got.

#710 Update ENI limits to match documentation
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#713 Add support for listening on unix socket for introspection endpoint
  README.md
  ipamd/introspect.go
Labels: enhancement

#698 Add run-integration-tests.sh script
  go.mod
  scripts/lib/cluster.sh
  scripts/run-integration-tests.sh
  test/integration/go.mod
  test/integration/go.sum
  test/integration/integration_test.go
Labels: testing

#716 Scope watch on "pods" to only pods associated with the local node
  pkg/k8sapi/discovery.go
Labels: enhancement

#729 Remove deprecated session.New method
  pkg/ec2metadata/client.go
  pkg/ec2metadatawrapper/ec2metadatawrapper.go
Labels: tech debt

#734 Additional tags to ENI
  README.md
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
Labels: enhancement
