Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-04, with the labels that each got.

#368 Update calico.yaml for 1.3 branch
  config/v1.3/calico.yaml
  config/v1.4/calico.yaml
Labels: calico

#378 Move build to go mod
  Gopkg.lock
  Gopkg.toml
  Makefile
  go.mod
  go.sum
  scripts/dockerfiles/Dockerfile.release
Labels: tech debt

#379 Use RouteReplace instead of RouteAdd
  pkg/networkutils/network.go
  plugins/routed-eni/driver/driver.go
  plugins/routed-eni/driver/driver_test.go
Labels: tech debt

#384 Exclude the tar file when re-running the script
  scripts/aws-cni-support.sh
Labels: enhancement

#395 Reinstate FELIX_IPTABLESMANGLEALLOWACTION and clear cpu req
  config/v1.3/calico.yaml
Labels: bug, calico

#387 Clean up function names, no change in functionality.
  ipamd/datastore/data_store.go
  ipamd/datastore/data_store_test.go
  ipamd/introspect.go
  ipamd/ipamd.go
Labels: tech debt

#406 Adding additional CRD for Calico that was missing.
  config/v1.4/calico.yaml
Labels: calico

#410 Adding additional CRD for Calico that was missing.
  config/v1.4/calico.yaml
Labels: calico

#414 Build improvements
  .travis.yml
  Makefile
  scripts/dockerfiles/Dockerfile.test
Labels: enhancement

#422 Support for unassigning IPs
  .travis.yml
  go.mod
  go.sum
  ipamd/ipamd.go
  ipamd/ipamd_test.go
  pkg/awsutils/awsutils.go
  pkg/awsutils/mocks/awsutils_mocks.go
  pkg/ec2wrapper/client.go
  pkg/ec2wrapper/mocks/ec2wrapper_mocks.go
Labels: enhancement, tech debt
