Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-03, with the labels that each got.

#342 add support for stdout logging
  README.md
  pkg/utils/logger/logger.go
  pkg/utils/logger/logger_test.go
Labels: enhancement

#340 Set mainENIRule mask
  pkg/networkutils/network.go
Labels: bug, calico

#351 Run yum clean all to reduce image size
  scripts/dockerfiles/Dockerfile.release
Labels: enhancement

#360 Retry LinkByMac when link not found (master)
  pkg/networkutils/network.go
  pkg/networkutils/network_test.go
Labels: bug, enhancement, tech debt

#362 Run dep ensure to clean up lockfile
  Gopkg.lock
Labels: tech debt

#361 Actually enable prometheus metrics
  pkg/awsutils/awsutils.go
Labels: enhancement, tech debt

#367 Use replace when adding host route
  ipamd/datastore/data_store.go
  ipamd/datastore/data_store_test.go
  ipamd/ipamd.go
  pkg/awsutils/awsutils.go
  pkg/netlinkwrapper/mocks/netlinkwrapper_mocks.go
  pkg/netlinkwrapper/netlink.go
  pkg/networkutils/network.go
  plugins/routed-eni/driver/driver.go
  scripts/mockgen
Labels: bug, tech debt

#366 Add new instance types
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement
