Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-12, with the labels that each got.

#714 Use CRI to obtain pod sandbox IDs instead of Kubernetes API
  go.mod
  go.sum
  ipamd/datastore/data_store.go
  ipamd/datastore/data_store_test.go
  ipamd/ipamd.go
  ipamd/ipamd_test.go
  ipamd/rpc_handler.go
  ipamd/rpc_handler_test.go
  pkg/cri/cri.go
  pkg/cri/generate_mocks.go
  pkg/cri/mocks/cri_mocks.go
  pkg/k8sapi/discovery.go
  plugins/routed-eni/cni.go
Labels: bug, priority/P0

#750 Treating ErrUnknownPod from ipamd to be a noop
  plugins/routed-eni/cni.go
Labels: bug

#726 Add support for a 'no manage' tag
  README.md
  ipamd/ipamd.go
  ipamd/ipamd_test.go
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/mocks/awsutils_mocks.go
  pkg/ec2wrapper/mocks/ec2wrapper_mocks.go
  pkg/netlinkwrapper/mock_netlink/link_mocks.go
  pkg/netlinkwrapper/mocks/netlinkwrapper_mocks.go
  pkg/networkutils/mocks/network_mocks.go
  pkg/utils/ttime/mocks/time_mocks.go
  rpc/mocks/rpc_mocks.go
Labels: enhancement

#751 Use dockershim.sock for CRI
  config/v1.5/aws-k8s-cni.yaml
  go.mod
  ipamd/datastore/data_store.go
  ipamd/ipamd.go
  pkg/cri/cri.go
  scripts/entrypoint.sh
Labels: bug

#769 Copy all files in the same command to remove a layer
  scripts/dockerfiles/Dockerfile.metrics
Labels: enhancement

#779 Generate limits file from EC2 API
  Makefile
  go.mod
  go.sum
  pkg/awsutils/gen_vpc_ip_limits.go
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#782 Add fallback to fetch limits from EC2 API
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/gen_vpc_ip_limits.go
  pkg/ec2wrapper/client.go
  pkg/ec2wrapper/mocks/ec2wrapper_mocks.go
Labels: enhancement

#781 Speed up tests using exponential backoff
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/publisher/publisher_test.go
Labels: enhancement, testing
