Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2019-09, with the labels that each got.

#598 Fix documentation issue for cni metrics agent
  cni-metrics-helper/README.md
Labels: documentation

#605 Fixed cniVersion in the plugin configuration file - Issue #604
  misc/10-aws.conflist
Labels: bug

#618 Make documentation easier to read
  README.md
  cni-metrics-helper/README.md
Labels: documentation

#621 Add support for g4dn instance family
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#626 Added retryNbackoff for tagENI method
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
Labels: enhancement

#627 Add inCoolingPeriod for AddressInfo
  ipamd/datastore/data_store.go
Labels: enhancement

#624 Clean up leaked ENIs in the background
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
Labels: enhancement

#632 Release v1.5.4
  CHANGELOG.md
  config/v1.5/aws-k8s-cni-1.10.yaml
  config/v1.5/aws-k8s-cni.yaml
Labels: documentation
