Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2020-03, with the labels that each got.

#844 scripts/lib: use v0.6.8
  scripts/lib/aws.sh
  scripts/lib/cluster.sh
Labels: testing

#857 Bump Calico to v3.13.0
  config/v1.6/calico.yaml
Labels: calico

#837 Support architecture targeted builds
  .circleci/config.yml
  .dockerignore
  .gitignore
  Makefile
  scripts/dockerfiles/Dockerfile.metrics
  scripts/dockerfiles/Dockerfile.release
  scripts/dockerfiles/Dockerfile.test
Labels: enhancement

#870 Mock /proc/sys
  pkg/networkutils/network.go
  pkg/networkutils/network_test.go
  pkg/procsyswrapper/generate_mocks.go
  pkg/procsyswrapper/mocks/procsys_mocks.go
  pkg/procsyswrapper/procsys.go
Labels: tech debt

#885 update cluster-proportional-autoscaler to 1.7.1
  config/v1.6/calico.yaml
Labels: calico
