Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2020-08, with the labels that each got.

#1110 Remove old pre-1.3 migration code
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/mocks/awsutils_mocks.go
  pkg/ipamd/ipamd.go
  pkg/ipamd/ipamd_test.go
  pkg/networkutils/mocks/network_mocks.go
  pkg/networkutils/network.go
  pkg/networkutils/network_test.go
Labels: tech debt

#1111 Remove references to unused metadata `owner-id`
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
Labels: tech debt

#1115 Slash and burn unused code
  pkg/awsutils/awsutils.go
  pkg/cninswrapper/generate_mocks.go
  pkg/cninswrapper/mocks/cninswrapper_mocks.go
  pkg/cninswrapper/ns.go
  pkg/k8sapi/discovery.go
  pkg/k8sapi/generate_mocks.go
  pkg/k8sapi/mocks/k8sapi_mocks.go
  pkg/netlinkwrapper/netlink.go
  pkg/utils/retry/errors.go
  pkg/utils/ttime/ttime.go
Labels: tech debt

#1138 Fix a log message
  pkg/ipamd/datastore/data_store.go
Labels: tech debt

#1149 Use our vendored version of protoc-gen-go
  Makefile
  rpc/rpc.pb.go
  scripts/protoc-gen-go
Labels: tech debt

#1151 Fix perf test bucket name
  scripts/lib/performance_tests.sh
  test/integration/README.md
Labels: testing

#1168 cherry-pick - Revert eni name change because of calico dependency
  cmd/routed-eni-cni-plugin/cni.go
Labels: calico

#1165 Update Calico to v3.15.1 & set routeSource=WorkloadIPs
  config/master/calico.yaml
Labels: calico

#1163 Update the k8s-tester and kubernetes version for e2e tests
  .circleci/config.yml
  scripts/lib/aws.sh
  scripts/run-integration-tests.sh
Labels: testing
