Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2020-09, with the labels that each got.

#1182 Update Calico images to v3.15.1 & set routeSource=WorkloadIPs for v1.7
  config/v1.7/calico.yaml
Labels: calico

#1186 Mount /run/xtables.lock to prevent unwanted race conditions.
  config/master/aws-k8s-cni-cn.yaml
  config/master/aws-k8s-cni-us-gov-east-1.yaml
  config/master/aws-k8s-cni-us-gov-west-1.yaml
  config/master/aws-k8s-cni.yaml
  config/master/manifests.jsonnet
Labels: bug

#1190 Update changelog
  CHANGELOG.md
Labels: documentation

#1201 Add ENABLE_POD_ENI to the readme
  README.md
Labels: documentation

#1195 Add GitHub workflows for testing
  .github/workflows/cron-test.yml
  .github/workflows/forked-pr-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  scripts/lib/aws.sh
  scripts/lib/cluster.sh
  scripts/lib/integration.sh
  scripts/run-integration-tests.sh
Labels: testing

#1193 Updated the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1197 Fix statcheck issues
  go.mod
  go.sum
  scripts/gen_vpc_ip_limits.go
  test/cmd/packet-verifier/packet-verifier.go
Labels: tech debt

#1219 Add t4g instance type
  misc/eni-max-pods.txt
  pkg/awsutils/vpc_ip_resource_limit.go
Labels: enhancement

#1221 Update readme to explain DISABLE_TCP_EARLY_DEMUX
  README.md
Labels: documentation

#1196 Fix all golint issues
  Makefile
  pkg/awsutils/awsutils.go
  pkg/grpcwrapper/client.go
  pkg/ipamd/datastore/data_store.go
  pkg/ipamd/introspect.go
  pkg/ipamd/ipamd.go
  pkg/ipamd/metrics.go
  pkg/ipamd/rpc_handler.go
  pkg/ipwrapper/ip.go
  pkg/k8sapi/discovery.go
  pkg/networkutils/network.go
  pkg/nswrapper/ns.go
  pkg/procsyswrapper/procsys.go
  pkg/rpcwrapper/client.go
  pkg/typeswrapper/client.go
  pkg/utils/logger/config.go
  pkg/utils/retry/backoff.go
  pkg/utils/retry/errors.go
  pkg/utils/retry/retry.go
  pkg/utils/retry/retry_test.go
Labels: tech debt

#1225 Refactor EC2 Metadata (IMDS) code into new typed accessor library
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/imds.go
  pkg/awsutils/imds_test.go
  pkg/awsutils/mocks/awsutils_mocks.go
  pkg/ec2metadata/client.go
  pkg/ec2metadata/generate_mocks.go
  pkg/ec2metadata/mocks/ec2metadata_mocks.go
  pkg/ipamd/ipamd.go
  pkg/ipamd/ipamd_test.go
Labels: tech debt

#1113 Avoid caching dynamic VPC CIDR info
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/mocks/awsutils_mocks.go
  pkg/ipamd/ipamd.go
  pkg/ipamd/ipamd_test.go
  pkg/ipamd/rpc_handler.go
  pkg/ipamd/rpc_handler_test.go
Labels: tech debt

#1231 Add some package level documentation
  cmd/aws-k8s-agent/main.go
  cmd/cni-metrics-helper/main.go
  cmd/grpc-health-probe/main.go
  cmd/routed-eni-cni-plugin/cni.go
  cmd/routed-eni-cni-plugin/driver/driver.go
  pkg/awsutils/awsutils.go
  pkg/awsutils/imds.go
  pkg/awsutils/imds_test.go
  pkg/cri/cri.go
  pkg/ec2metadatawrapper/mocks/ec2metadatawrapper_mocks.go
  pkg/grpcwrapper/client.go
  pkg/ipwrapper/ip.go
  pkg/netlinkwrapper/netlink.go
  pkg/networkutils/network.go
  pkg/nswrapper/ns.go
  pkg/procsyswrapper/procsys.go
  pkg/rpcwrapper/client.go
  pkg/typeswrapper/client.go
  pkg/utils/logger/logger.go
  pkg/utils/retry/retry.go
  test/cmd/packet-verifier/packet-verifier.go
Labels: documentation
