Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2020-10, with the labels that each got.

#1237 Avoid detaching EFA ENIs
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
  pkg/awsutils/mocks/awsutils_mocks.go
  pkg/ipamd/datastore/data_store.go
  pkg/ipamd/datastore/data_store_test.go
  pkg/ipamd/ipamd.go
  pkg/ipamd/ipamd_test.go
Labels: enhancement

#1242 Ignore error on enabling TCP early demux for old kernels
  README.md
  scripts/init.sh
Labels: bug

#1244 Release 1.7.4
  CHANGELOG.md
  config/v1.7/aws-k8s-cni-cn.yaml
  config/v1.7/aws-k8s-cni-us-gov-east-1.yaml
  config/v1.7/aws-k8s-cni-us-gov-west-1.yaml
  config/v1.7/aws-k8s-cni.yaml
  config/v1.7/cni-metrics-helper-cn.yaml
  config/v1.7/cni-metrics-helper-us-gov-east-1.yaml
  config/v1.7/cni-metrics-helper-us-gov-west-1.yaml
  config/v1.7/cni-metrics-helper.yaml
Labels: config

#1247 Match primary ENI IP correctly
  scripts/init.sh
Labels: bug

#1235 Update calico to v3.16.2
  config/master/calico.yaml
Labels: calico

#1240 Fix lint issues and enable test check
  .travis.yml
  cmd/routed-eni-cni-plugin/driver/driver.go
  pkg/awsutils/awsutils.go
  pkg/cri/cri.go
  pkg/grpcwrapper/client.go
  pkg/ipwrapper/ip.go
  pkg/netlinkwrapper/netlink.go
  pkg/networkutils/network.go
  pkg/nswrapper/ns.go
  pkg/procsyswrapper/procsys.go
  pkg/rpcwrapper/client.go
  pkg/typeswrapper/client.go
  pkg/utils/logger/logger.go
  pkg/utils/retry/retry.go
Labels: documentation

#1228 Add some minimal tests to metrics
  .github/.codecov.yml
  cmd/cni-metrics-helper/metrics/cni_metrics_test.go
  pkg/k8sapi/generate_mocks.go
  pkg/k8sapi/mocks/k8sapi_mocks.go
Labels: tech debt
