Repository aws/amazon-vpc-cni-k8s, pull requests merged in 2020-04, with the labels that each got.

#892 Add missing permissions in typha-cpha sa (Calico)
  config/v1.6/calico.yaml
Labels: calico

#915 ensure non-nil Attachment in getENIAttachmentID
  pkg/awsutils/awsutils.go
  pkg/awsutils/awsutils_test.go
Labels: bug

#912 Ensure makefile exits with non-zero code when code is unformatted
  Makefile
Labels: bug

#913 Add code coverage reports
  .circleci/config.yml
  .codecov.yml
  Makefile
Labels: enhancement, testing

#919 Use -buildmode=pie for binaries
  .circleci/config.yml
  Makefile
Labels: enhancement

#925 Add additional documentation around IPs and ENIs
  README.md
  docs/eni-and-ip-target.md
Labels: documentation
